### ISSUE TITLE
Script data.py

### ISSUE THREAD

**Issue by danielelic** [vrai-group/infant-dnn#1]
# Data

Caricare le immagini contenute dentro la cartella `raw/` in file `npy`.

**Comment by lucav48** [comment]
Abbiamo completato lo script `data.py`. Vengono creati tre file `.npy` di train rispettivamente per:
- le immagini 16 bit.
- le immagini 8 bit.
- le maschere.

Abbiamo creato la seguente struttura: dentro la cartella `raw` è presente una directory `train`. All'interno di essa abbiamo inserito due ulteriori cartelle `positive` e `partial`. 
Nello script le due cartelle vengono considerate come un'unica directory.

**Comment by danielelic** [comment]
Raccogliere tutti gli `id` delle immagini in `ids_train.npy`. 

- Creare una lista `ids = []` 
- Aggiungere il nome di ogni immagine nel cui nome è contenuta la parola `_mask` (es. `positive/YYYYMMDD-hhmmss_zzzzz`) alla lista `ids`
- Convertire la lista `ids = np.array(ids, dtype=object)`
- Salvare `ids` in `ids_train.npy`

**Comment by lucav48** [comment]
Abbiamo appena completato questa parte. Ora viene creato un nuovo `.npy` contenente tutti gli `id` di ogni immagine coinvolta nello script.
