### ISSUE TITLE
Script train.py

### ISSUE THREAD

**Issue by danielelic** [vrai-group/infant-dnn#2]
# Train

## Preprocessing

Definire la funzione `preprocess` in modo da poter fare il `resize` delle immagini.

## Dataset Split

Usate parte del vostro dataset per la fase di test. Date uno sguardo alla funzione:
http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

Avrete una cosa del genere:
```
images_train, images_test, masks_train, masks_test, ids_train, ids_test = train_test_split(images, masks, ids, stratify=map(lambda x: x.sum() > 0, masks), test_size=0.2)
```

## U-Net

Definire la rete U-Net con la funzione `get_unet`.

**Comment by matteosartori** [comment]
Abbiamo completato il `data.py` in modo da caricare le immagini di train e test con la funzione random suggerita, impostando come quantità per i test il 10% delle immagini già preparate.

Abbiamo poi preparato il `train.py`.
In particolare abbiamo inserito la funzione `preprocess` (lasciando il `resize` delle immagini a `96x96`) ed la `get_unet()` che definisce il modello della rete.
Infine la funzione `train_and_predict()` è stata modificata ed adattata sia per le immagini a 16 che ad 8 bit.
Abbiamo notato che da aprile 2017 le librerie necessarie al lancio dello script sono cambiate, sostituendo a `Theano` la libreria `TensorFlow` che sembra sia supportata solo in `Python 3.x` e necessita di librerie `CUDA`.

Proviamo ad installare il tutto e vedere se funziona o hai qualcosa da suggerirci?

**Comment by danielelic** [comment]
Iniziate a fare i test e a cercare la configurazione migliore della rete.

**Comment by JacopoZincarini** [comment]
Allenando la rete con 1214 immagini totali, di cui il 90% usate per il train e il restante 10% per il test, abbiamo trovato la seguente configurazione per la rete:
-Epoche = 50
-Validation split = 0.1
-Batch size = 1
Abbiamo inoltre creato la funzione `evaluate_result()` per determinare l'accuratezza delle immagini predette. Ogni immagine predetta è stata confrontata con l'immagine creata manualmente da noi, in particolare è stata calcolata la percentuale di pixels esatti rispetto al totale.
In questo modo è stata raggiunta una percentuale di 97,4% su circa 120 immagini di test e un `dice_coefficient` pari a 0.9559

Una volta allenata la rete neurale con tutte le immagini (3 ore circa) abbiamo creato lo script `test.py` per velocizzare le operazioni di testing su altre immagini senza dover riallenare la rete. Infatti tutti i file `npy` e il file `weights.h5` sono stati inseriti nella cartella `infantdnn/trained_model` e vengono caricati da questo script (testando il modello su 600 immagini è stato ottenuta una precisione del 96.8%)
